---
title: "Proyecto SNV1"
author: "Alejandro Brenes, Santiago Fernández, Eyeri Méndez y Erick Venegas"
date: "`r Sys.Date()`"
output: html_document
---

# Introducción

Se cargan las librerías necesarias.

```{r librerias}
pacman::p_load(ggplot2,
               readxl,
               cowplot)
```

Se lee la base de incendios forestales en Argelia.

```{r base_incendios}
incendios <- read_excel("data/Incendios.xlsx")

# Se cambia el nombre de las categorías de la variable Classes
incendios$Classes <- factor(incendios$Classes,
                            levels = c("not fire", "fire"),
                            labels = c("Sin incendio", "Con incendio"))
```

# Resumen descriptivo y análisis de correlación

A

# Gráficos

Se procede a realizar distintos gráficos entre las variables de la base.

## DMC vs. FFMC

```{r DMC_FFMC}
ggplot(incendios, aes(x = FFMC, y = DMC, color = Classes)) +
  geom_point() +
  labs(x = "FFMC",
       y = "DMC",
       color = "") +
  theme_cowplot()
```

## ISI vs. FFMC

```{r ISI_FFMC}
ggplot(incendios, aes(x = FFMC, y = ISI, color = Classes)) +
  geom_point() +
  labs(x = "FFMC",
       y = "ISI",
       color = "") +
  theme_cowplot()
```

## BUI vs. FFMC

```{r BUI_FFMC}
ggplot(incendios, aes(x = FFMC, y = BUI, color = Classes)) +
  geom_point() +
  labs(x = "FFMC",
       y = "BUI",
       color = "") +
  theme_cowplot()
```




